### ISSUE TITLE
Multiple receivers simultaneously

### ISSUE THREAD

**Issue by helioshk** [lazywalker/DigiSkimmer#12]
Hi,
Is it possible to use two (or more) receivers simultaneously?
I have defined two receivers, kiwi and kiwi2.
The schedule is
```
SCHEDULES = {
     '*': {'kiwi': [80, 60, 40, 30, 20, 17, 15, 12]},
     '*': {'kiwi2': ['80!']}
     }
```
Now it is only running WSPR on kiwi2, FT8 on kiwi is not used.

**Comment by lazywalker** [comment]
Hi, you can use setting like below:
```
SCHEDULES = {
  '*': {
     'kiwi': [80, 60, 40, 30, 20, 17, 15, 12]},
     'kiwi2': ['80!']
  }
}
```

**Comment by helioshk** [comment]
Ah, brilliant. Thank you! 
Now it works.
