### ISSUE TITLE
Possible typos in the settings.py.template file?

### ISSUE THREAD

**Issue by ngmacha** [lazywalker/DigiSkimmer#15]
Hello and thank you very much for a great tool - I've wanted to try my hands with FT8/FT4 for a long time, and since yesterday running your DigiSkimmer for less than 24 hours already had more than 1500 reports from 77 countries on pskreporter!!

The setting up was quite easy, I was just following, word by word, the README instructions. But I kept getting errors for a while, that finally I've traced to the 'czsdr' labels in the settings.py.template. Changing them all to 'szsdr' fixed everything. 

Not sure if this is only my system (Debian 11 freshly installed on a Hyper-V virtual machine running off a Windows 10 PC, connecting to the original KiWiSDR with v.1.461 software on the same local network), or these are typos in the settings.py.template and README files. If the latter, correcting the files may help other enjoy more your great software.

Thank you and kind regards - Mac Ha

**Comment by lazywalker** [comment]
Hi, many thanks for you advice, yes the demo site czsdr is down for a while, i'll remove it from the template
73
