### ISSUE TITLE
After running several days, all CPUs maxed out at 100%....

### ISSUE THREAD

**Issue by frohro** [lazywalker/DigiSkimmer#16]
I'm not sure what happened, but rebooting fixed it.  It happened twice so far.  I have been using it only about a week, so it took three or four days to happen.  Last time I was in a video meeting, so I could not debug the problem further.  I will try again to see what happens.

**Comment by lazywalker** [comment]
try using 
$ top 

to find out which process took you CPUs

**Comment by frohro** [comment]
I've been running it for a week now, and am unable to duplicate the problem, so I'm closing this issue.
