### ISSUE TITLE
2048 requested and 0 written Error?

### ISSUE THREAD

**Issue by frohro** [lazywalker/DigiSkimmer#20]
Hi,
I've been running Digiskimmer for months with no problems.  Tonight I went to look at spots, and am getting an error.  The number of the error doesn't seem to be relevant, as it changes when I stop and restart fetch.py.  The messages are 2048 requested and 0 written after the error number.  Any tips on what might be going on?
Thanks,
Rob
KL7NA

**Comment by frohro** [comment]
I found this only happens on one machine.  I can still run ./fetch.py on another machine just fine.  I suspect something became corrupted there somehow.

**Comment by lazywalker** [comment]
hi, can you check the free disk space of that machine encountered errors? use df cmd.

**Comment by frohro** [comment]
Full disk was the issue.  Thanks for the tip.
