### ISSUE TITLE
WARNING 787501 [kl7na-10|10+|10!|80|80+|80!] kiwisdr.local:8073 too busy now. Reconnecting after 15 seconds

### ISSUE THREAD

**Issue by frohro** [lazywalker/DigiSkimmer#21]
Hi All,
I suspect I have something wrong in my schedules in settings.py.  Maybe someone can help me figure out what to do to fix it.  

I get these warnings over and over again:
`2022-05-05 21:33:53,300 WARNING 788622 [kl7na-12|12+|12!] kiwisdr.local:8073 too busy now. Reconnecting after 15 seconds
2022-05-05 21:33:53,343 WARNING 788622 [kl7na-20|20+|20!] kiwisdr.local:8073 too busy now. Reconnecting after 15 seconds
2022-05-05 21:33:53,376 WARNING 788622 [kl7na-17|17+|17!] kiwisdr.local:8073 too busy now. Reconnecting after 15 seconds
2022-05-05 21:33:53,398 WARNING 788622 [kl7na-30|30+|30!] kiwisdr.local:8073 too busy now. Reconnecting after 15 seconds
2022-05-05 21:33:53,427 WARNING 788622 [kl7na-40|40+|40!] kiwisdr.local:8073 too busy now. Reconnecting after 15 seconds
2022-05-05 21:33:53,469 WARNING 788622 [kl7na-15|15+|15!] kiwisdr.local:8073 too busy now. Reconnecting after 15 seconds
2022-05-05 21:33:53,511 WARNING 788622 [kl7na-10|10+|10!|80|80+|80!] kiwisdr.local:8073 too busy now. Reconnecting after 15 seconds
/home/frohro/Projects/DigiSkimmer/./fetch.py:200: DeprecationWarning: getName() is deprecated, get the name attribute instead
`
I do get plenty of spots, but the warnings bother me, because it appears I messed up the settings.py somehow.
From settings.py:

`SCHEDULES = {
     '*': {'kl7na': ['12|12+|12!', '15|15+|15!', '17|17+|17!', '20|20+|20!', '30|30+|30!', '40|40+|40!', '10|10+|10!|80|80+|80!']},

    # simple used:
    # '21:00-08:00': {'czsdr': [20, 30, 40, 60, 80, 160]},
    # '08:00-14:30': {'czsdr': [10, 12, 15, 17, 20, 30]},
    # '14:30-21:00': {'czsdr': [10, 15, 17, 20, 30, 40]},

    # band hops example:
    # # four slots all FT8, the last one is rotate between 60-80-160 when localtime is 21:00-08:00
    # '21:00-08:00': {'szsdr': [20, 30, '40~', '60|80|160']},    
    # # when localtime is 08:00-12:00
    # '08:00-12:00': {
    #     # station no.1, slot1 is rotate between 20(FT8)-20(FT4), slot3 is 40(FT8)-40(FT4)
    #     'szsdr': ['20|20+', 30, '40~|40+', '60|80|160'],

    #     # station no.2, slot1 is rotate between 10-12-15-17-20-30-40 at mode FT8, then 20-30-40 at mode FT4
    #     'czsdr': ['10|12|15|17|20|30|40|20+|30+|40+'],
    # }
`
Any suggestions?

Thanks,
rob

**Comment by doccodyblue** [comment]
Hey Rob,

for me it looks like you are starting 7 receiving threads in parallel.
That results in having 7 listeners on the KiWi which it simply will not handle. At least not in default setup. I don't think that this is your intention anyway. 

You should instead rotate between the bands and use maybe 2 receivers.

like:
'kl7na': ['12|12+|12!|15|15+|15!|17|17+|17!|20|20+|20!', '30|30+|30!|40|40+|40!|10|10+|10!|80|80+|80!']},
(didn't check that line, but you get the idea.)

This should use 2 receivers and rotate them. Try it. It may be not that efficient though. 


Best,
Andy

**Comment by frohro** [comment]
Thanks @doccodyblue.  I think you are right.  Let's close this.
