### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by helioshk** [lazywalker/DigiSkimmer#33]
I upgraded to debian bookworm and now i get depreciation warnings when running digiskimmer:

fetch.py:30: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  threading.currentThread().setName("main")

fetch.py:30: DeprecationWarning: setName() is deprecated, set the name attribute instead
  threading.currentThread().setName("main")

etch.py:200: DeprecationWarning: getName() is deprecated, get the name attribute instead
  if r.getName() == "%s-%s" % (st, band):
  
  
  This should fix it:
```
30c30
< threading.currentThread().setName("main")
---
> threading.current_thread().name = "main"
136c136
<     [t.join() for t in threading.enumerate() if t is not threading.currentThread()]
---
>     [t.join() for t in threading.enumerate() if t is not threading.current_thread()]
200c200
<                             if r.getName() == "%s-%s" % (st, band):
---
>                             if r.name == "%s-%s" % (st, band):
```

**Comment by lazywalker** [comment]
#32 and the recently commit fix this issue. thanks :)
