### ISSUE TITLE
No upload to pskreporter After a few hours of running

### ISSUE THREAD

**Issue by hikijun** [lazywalker/DigiSkimmer#9]
Hello! I am testing digiskimmer with KiwiSDR.
After a few hours, it is not uploading to pskreporter. When I Ctrl-C to stop, it uploads many thousands at the end, as shown below.

Regards, Kijun/HL3AMO

-----------
2021-01-14 22:59:46,655 INFO      1 [QW-1] [hikijun1] FT8 T225915 DB-20.0 DT0.7 F7.074604 K7XB JH1LAH -11 : - 
2021-01-14 22:59:46,656 INFO      1 [QW-1] [hikijun1] FT8 T225915 DB-10.0 DT0.5 F7.075500 W9CSX YC9VM -14 : - 
2021-01-14 22:59:46,657 INFO      1 [main] KeyboardInterrupt: threads successfully closed
2021-01-14 22:59:50,282 WARNING     1 [psk.uploader-hikijun1] uploading 36185 spots

**Comment by lazywalker** [comment]
HI, did you use wifi connection? i'll try to reproduce this issue.

**Comment by hikijun** [comment]
No, connected to 1Gb ethernet. And the device is RPi4.

Kijun Park (박기준)

________________________________
보낸 사람: lazywalker <notifications@github.com>
보냄: 2021년 1월 15일 금요일 05:12
받는 사람: lazywalker/DigiSkimmer
참조: Kijun; Author
제목: Re: [lazywalker/DigiSkimmer] No upload to pskreporter After a few hours of running (#9)


HI, did you use wifi connection? i'll try to reproduce this issue.

**Comment by lazywalker** [comment]
I've apply patches to master, can you try the latest commit to see if this issue can be solved?

Thanks

**Comment by hikijun** [comment]
Moved old files to another directory and installed fresh from git.
Edited settings.py as usual 3 worker and now it is on-line.  Let you know after more than 10 hours later or tomorrow.
It will be great if I could monitor non standard frequencies.
Thanks!


Windows 10용 메일<https://go.microsoft.com/fwlink/?LinkId=550986>에서 보냄

보낸 사람: lazywalker<mailto:notifications@github.com>
보낸 날짜: 2021년 1월 15일 금요일 오전 11:55
받는 사람: lazywalker/DigiSkimmer<mailto:DigiSkimmer@noreply.github.com>
참조: Kijun<mailto:hikijun@hotmail.com>; Author<mailto:author@noreply.github.com>
제목: Re: [lazywalker/DigiSkimmer] No upload to pskreporter After a few hours of running (#9)


I've apply patches to master, can you try the latest commit to see if this issue can be solved?

Thanks

**Comment by hikijun** [comment]
Re-installed, up and running. You may see it working from PSKREPORTER site.  Kijun

Windows 10용 메일<https://go.microsoft.com/fwlink/?LinkId=550986>에서 보냄

보낸 사람: lazywalker<mailto:notifications@github.com>
보낸 날짜: 2021년 1월 15일 금요일 오전 11:55
받는 사람: lazywalker/DigiSkimmer<mailto:DigiSkimmer@noreply.github.com>
참조: Kijun<mailto:hikijun@hotmail.com>; Author<mailto:author@noreply.github.com>
제목: Re: [lazywalker/DigiSkimmer] No upload to pskreporter After a few hours of running (#9)


I've apply patches to master, can you try the latest commit to see if this issue can be solved?

Thanks

**Comment by hikijun** [comment]
Hello!
Look like it is working OK.  I just see an unexpected close of the terminal window. Re-booted and running OK.
Just modified settings.py to see the FT4 but getting some errors as shown below.
Regards,  Kijun

2021-01-16 15:42:47,644 INFO   1870 [QW-2] [hikijun1] FT8 T154230 DB-17.0 DT0.4 F18.102328 3B8FA JA6OXT PM53 : JA6OXT PM53
2021-01-16 15:42:47,645 INFO   1870 [QW-2] [hikijun1] FT8 T154230 DB-14.0 DT0.4 F18.102441 CQ VK4CUZ QG48 : VK4CUZ QG48
error: unrecognised option: --ft44:[..........]
2021-01-16 15:42:53,162 ERROR  1870 [QW-0] error while parsing wsjt message
Traceback (most recent call last):
  File "/home/pi/DigiSkimmer/digiskr/wsjt.py", line 129, in parse
    out = decoder.parse(msg, freq)
  File "/home/pi/DigiSkimmer/digiskr/wsjt.py", line 224, in parse
    "timestamp": self.parse_timestamp(msg[0:4], "%H%M"),
  File "/home/pi/DigiSkimmer/digiskr/wsjt.py", line 153, in parse_timestamp
    ts = datetime.strptime(instring, dateformat)
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data ' Usa' does not match format '%H%M'
2021-01-16 15:42:53,163 ERROR  1870 [QW-0] error while parsing wsjt message
Traceback (most recent call last):
  File "/home/pi/DigiSkimmer/digiskr/wsjt.py", line 129, in parse
    out = decoder.parse(msg, freq)
  File "/home/pi/DigiSkimmer/digiskr/wsjt.py", line 224, in parse
    "timestamp": self.parse_timestamp(msg[0:4], "%H%M"),
  File "/home/pi/DigiSkimmer/digiskr/wsjt.py", line 153, in parse_timestamp
    ts = datetime.strptime(instring, dateformat)
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '    ' does not match format '%H%M'
2021-01-16 15:42:53,164 ERROR  1870 [QW-0] failed to decode job
Traceback (most recent call last):
  File "/home/pi/DigiSkimmer/digiskr/base.py", line 55, in run
    job.run()
  File "/home/pi/DigiSkimmer/digiskr/base.py", line 26, in run
    self.decoder.decode(self)
  File "/home/pi/DigiSkimmer/digiskr/audio.py", line 76, in decode
    self._parser.parse(messages)
  File "/home/pi/DigiSkimmer/digiskr/wsjt.py", line 125, in parse
    if msg[21] in modes or msg[19] in modes:
IndexError: string index out of range
2021-01-16 15:43:00,100 WARNING  1870 [hikijun1-20|20+] switching to FT8-20m
2021-01-16 15:43:00,155 WARNING  1870 [hikijun1-30|40] switching to FT8-40m
2021-01-16 15:43:01,660 INFO   1870 [QW-0] [hikijun1] FT8 T154245 DB-6.0 DT0.2 F18.100942 9H1ET VK3ZW PG77 : VK3ZW PG77
2021-01-16 15:43:01,660 INFO   1870 [QW-0] [hikijun1] FT8 T154245 DB3.0 DT0.4 F18.101041 JA6OXT R0SBC OO22 : R0SBC OO22



Windows 10용 메일<https://go.microsoft.com/fwlink/?LinkId=550986>에서 보냄

보낸 사람: lazywalker<mailto:notifications@github.com>
보낸 날짜: 2021년 1월 15일 금요일 오전 11:55
받는 사람: lazywalker/DigiSkimmer<mailto:DigiSkimmer@noreply.github.com>
참조: Kijun<mailto:hikijun@hotmail.com>; Author<mailto:author@noreply.github.com>
제목: Re: [lazywalker/DigiSkimmer] No upload to pskreporter After a few hours of running (#9)


I've apply patches to master, can you try the latest commit to see if this issue can be solved?

Thanks

**Comment by lazywalker** [comment]
it seem's your jt9 command doesn't support --ft4 param, would you please run jt9 command manually and post the result? 
post your settings(the SCHEDULES section) as well.

> error: unrecognised option: --ft44:[..........]

**Comment by hikijun** [comment]
This is my schedule section:
    # simple used:
     '19:00-08:30': {'hikijun1': ['20|30', 40, '80|160']},
     '08:30-15:30': {'hikijun1': ['10|12|15', 17, '20|30']},
     '15:30-19:00': {'hikijun1': ['10|12|15|17', '20|20+", '30|40']},

and I am looking for manual operation.

**Comment by lazywalker** [comment]
check this line below, should be `'20|20+'` or `"20|20+"`, quotation marks should close-up.
> '15:30-19:00': {'hikijun1': ['10|12|15|17', '20|20+", '30|40']},

**Comment by hikijun** [comment]
That, I corrected.  I am trying to reinstall newer version of wsjtx

**Comment by hikijun** [comment]
Uninstalling old stuff and Fresh installation wsjtx2.2.2 solved the problem.   Thanks!

**Comment by xcarcelle** [comment]
@lazywalker : I am finalized my set-up with kiwisdr and digiskimmer (with ubuntu) and running fetch.py gives me the ft8 logs messages but I would like to see the complete ft8 messages in wsjt-x but when I open wsjt-x there is not messages output there ? Is there something to set-up to link fetch.py and the gui of wsjt-x ?
Thanks for your great project !

**Comment by helioshk** [comment]
> I've apply patches to master, can you try the latest commit to see if this issue can be solved?

I can confirm that the upload issue has been solved. Running without problem since 3 days. Thank you very much.

**Comment by lazywalker** [comment]
> @lazywalker : I am finalized my set-up with kiwisdr and digiskimmer (with ubuntu) and running fetch.py gives me the ft8 logs messages but I would like to see the complete ft8 messages in wsjt-x but when I open wsjt-x there is not messages output there ? Is there something to set-up to link fetch.py and the gui of wsjt-x ?
> Thanks for your great project !

Hi, the digiskimmer was designed to run as a long-run multi-band spotter, we just set and forget it :)
with these settings you can save spots to files separated by date:
```
LOG_SPOTS = True
LOG_TO_FILE = True
```
if you want to save all conversation messages(not only the CQ transmissions) during of all operating bands to files, i can add this feature, just submit an new issue, since THIS one is already closed:)

But, the digiskimmer and the GUI wsjt-x are totally different processes so there is no way to link and use them together.
if you goal is use GUI wsjtx with KiwiSDR, you can open a KiwiSDR browser with wsjt-x, use the audio output from you computer and input it to wsjt-x, you should see the messages output there.

or, you may want to try https://www.blackcatsystems.com/software/kiwiSdr-sound-client-virtual-audio-device.html, there plugin can map a KiwiSDR as a virtual audio device.

Thanks for any feed back.

73
Michael

**Comment by xcarcelle** [comment]
@lazywalker : thanks for your prompt reply and :
- wsjt-x : thanks for the clarification and I will try to plug the audio output from kiwisdr to wsjt-x 
- blackcatsystems : i will give a try to this project to map a virtual audio device
- logs all messages issue : I created this issue https://github.com/lazywalker/DigiSkimmer/issues/10
Will keep you update and hope to receive more FT8 messages :)
